### ISSUE TITLE
我写张一川传，写了4000余字，结果你复制，声称你的，现在又反过来咬我一口，逼着我删除。有这样的吗？答：有

### ISSUE THREAD

**Issue by diandaokongge** [zzzzzyc/zzzzzyc.github.io#1]
# 我写张一川传，结果你复制，声称你的，现在又反过来咬我一口。

# 有这样的吗？

# 你向GitHub投诉去！

# @中国-北京-海淀区-老山西里-39号楼-7单元-3层-301室内的张一川

# https://diandaokongge.github.io/tuchuang/zyc-3000-2000

# 张一川本人的国际友好手势照片

![image](https://user-images.githubusercontent.com/94299076/166878034-e22d0b35-3e77-4af5-a6a2-38f5d660d86e.png)

**Comment by zzzzzyc** [comment]
我删除了。。。
